runtime: nodejs18  
env: standard     

instance_class: F1
service: default

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 15
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6